apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
  namespace: kongroo
  labels:
    app.kubernetes.io/name: payments-api
    app.kubernetes.io/instance: payments-api
    app.kubernetes.io/version: "0.0.3"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: kongroo
    app.kubernetes.io/managed-by: kubectl
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  RabbitMq__Host: "rabbitmq"
  Payments__ApprovalLimit: "1000.00"
