apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
type: Opaque
stringData:
  ConnectionStrings__Database: "Host=postgres;Database=kongroo_payments;Username=kongroo;Password=development"
  Jwt__SigningKey: "Development.SigningKey.AtLeast32Characters!"
  RabbitMq__User: "kongroo"
  RabbitMq__Pass: "development"
