apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
  namespace: kongroo
  labels:
    app.kubernetes.io/name: payments-api
    app.kubernetes.io/instance: payments-api
    app.kubernetes.io/version: "0.0.3"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: kongroo
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  ConnectionStrings__Database: "Host=postgres;Database=kongroo_payments;Username=kongroo;Password=development"
  RabbitMq__User: "kongroo"
  RabbitMq__Pass: "development"
