apiVersion: v1
kind: Service
metadata:
  name: payments-api
  namespace: kongroo
  labels:
    app.kubernetes.io/name: payments-api
    app.kubernetes.io/instance: payments-api
    app.kubernetes.io/version: "0.0.3"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: kongroo
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    app: payments-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
